#端口
server:
  port: 8881
spring:
  # 数据源
  profiles:
    active: druid
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
  # 时间戳
  jackson:
    date-format: yyyy-MM-DD hh:mm:ss
    time-zone: GMT+
  servlet:
    multipart:
      #上传文件大小
      max-file-size: 50MB
      max-request-size: 50MB
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/

  freemarker:
    check-template-location: false

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.**.bean
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
    #打印sql(语句)，方便调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/base/*